### ISSUE TITLE
Java Code Convention

### ISSUE THREAD

**Issue by ghost** [galinka-zch/zadanie-massiv#3]
http://www.oracle.com/technetwork/java/codeconventions-150003.pdf
1. Имя класса не соответствует Code Convention.
2. Использование фигурных скобочек не соответствует, везде должны быть присутствовать явно. 
3. [Йода стиль](https://ru.wikipedia.org/wiki/%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F_%D0%99%D0%BE%D0%B4%D1%8B) не канает, угадай где.
4. Использование конструкции `if(true==proverka){` избыточно, вместо этого следует использовать `if (proverka) {`.
5. Расставь пробелы между инструкциями и выражениями согласно рекомендациям и премарам файла. Например, вместо `for(int i=0; i<mas.length; i++)` должно быть `for (int i = 0; i < mas.length; i++)`

После того, как исправишь замечания, закрой эту задачу.

**Comment by ghost** [comment]
Дополнительно исправь название `control_sorting`, названия переменных в java по CodeConvention должны быть [CamelCase](https://ru.wikipedia.org/wiki/CamelCase) нотации.

**Comment by ghost** [comment]
1. В первом и последнем циклах нет фигурных скобочек.
2. В теле последнего цикла нет отступа.

**Comment by galinka-zch** [comment]
Антошечка, я поправила

Галина 
galinka_zch@mail.ru
