### ISSUE TITLE
Исправить алгоритм на строки

### ISSUE THREAD

**Issue by ghost** [galinka-zch/zadanie-massiv#4]
Входные данные переделать на массив строк.
Ключевая операция для сравнения двух чисел у тебя сейчас `mas[j-1]>mas[j]`. В случа со строками это будет что-то типа этого `mas[j-1].compareTo(mas[j]) > 0`. Тебе нужно заюзать метод compareTo или compareToIgnoreCase в зависимости от условий задачи, выбери.

Документацию по этим методам, можно посмотреть здесь:
- https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/String.html#compareTo(java.lang.String)
- https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/String.html#compareToIgnoreCase(java.lang.String)

**Comment by galinka-zch** [comment]
Сортировка строк пузырьком по возрастанию, т.е. по алфавиту
